spring:
  application:
    name: mock3
  # 数据源
  datasource:
    username: root
    password: QEjzECMFgk
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.19.32.126:32316/mock3?rewriteBatchedStatements=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 10.19.36.164:8848
        username: mcd
        password: 7Dq5aF_Bo#rRBC!
        namespace: de185e7c-5a0a-4691-a875-93bc17756d95
# mybatis-plus 配置
mybatis-plus:
  global-config:
    banner: true
    db-config:
      id-type: assign_id
      logic-delete-value: -1
      logic-not-delete-value: 1
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
# 日志
logging:
  level:
    cn.zaink.mock3: trace