apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock3
  labels:
    k8s.kuboard.cn/layer: svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock3
  template:
    metadata:
      labels:
        app: mock3
    spec:
      containers:
        - name: mock3
          image: registry.asiainfo.com:5000/mock3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP